select * FROM C_LOCATION a,C_BPARTNER_LOCATION b,C_BPARTNER c where a.C_LOCATION_ID=b.C_LOCATION_ID AND
c.C_BPARTNER_ID=b.C_BPARTNER_ID AND c.iscustomer='Y';

delete from C_BPARTNER_LOCATION  WHERE C_BPARTNER_LOCATION_ID IN (
	select b.C_BPARTNER_LOCATION_ID FROM C_LOCATION a,C_BPARTNER_LOCATION b,C_BPARTNER c where a.C_LOCATION_ID=b.C_LOCATION_ID AND
c.C_BPARTNER_ID=b.C_BPARTNER_ID AND c.iscustomer='Y'
);

delete from C_LOCATION WHERE C_LOCATION_ID IN (
	select a.C_LOCATION_ID FROM C_LOCATION a,C_BPARTNER_LOCATION b,C_BPARTNER c where a.C_LOCATION_ID=b.C_LOCATION_ID AND
c.C_BPARTNER_ID=b.C_BPARTNER_ID AND c.iscustomer='Y'
);